import { useMemo, useState } from 'react'
import { BookOpen, ChevronRight, ClipboardList, Download, Edit2, FilePlus2, FileText, History, Inbox, Newspaper, PenLine, Search, Send, ShieldCheck, Trash2 } from 'lucide-react'

const sections = [
  { key: 'Dashboard', label: 'Knowledge Dashboard', icon: BookOpen },
  { key: 'Manuals', label: 'Manuals', icon: FileText },
  { key: 'Service Bulletins', label: 'Service Bulletins', icon: ClipboardList },
  { key: 'Operator Bulletins', label: 'Operator Bulletins', icon: Newspaper },
  { key: 'Amendments leaflets', label: 'Amendments leaflets', icon: FilePlus2 },
  { key: 'In-coming Letters', label: 'In-coming Letters', icon: Inbox },
  { key: 'Out-going Letters', label: 'Out-going Letters', icon: Send },
  { key: 'Knowledge Articles', label: 'Knowledge Articles', icon: PenLine },
]

export const seedDocuments = [
  { id: 1, type: 'Manuals', code: 'ALS-MAN-001', title: 'ALS 50 Loitering Munition System Manual', system: 'SRLM', owner: 'Engineering Team', status: 'Published', version: '3.2', updated: '22 Jul 2026', effective: '01 Aug 2026', summary: 'Approved operating, maintenance, safety, and storage instructions for the ALS 50 system.', revisions: [{ version: '3.2', date: '22 Jul 2026', author: 'Vivek Nair', note: 'Updated maintenance intervals and battery storage guidance.' }, { version: '3.1', date: '15 Mar 2026', author: 'Vivek Nair', note: 'Added GCS recovery procedure.' }] },
  { id: 2, type: 'Manuals', code: 'ALS-MAN-014', title: 'Ground Control Station Operator Manual', system: 'GCS', owner: 'GCS', status: 'Published', version: '2.4', updated: '18 Jul 2026', effective: '18 Jul 2026', summary: 'Operator reference for startup, mission planning, telemetry, and shutdown.', revisions: [{ version: '2.4', date: '18 Jul 2026', author: 'Arvind Kapoor', note: 'Refined mission abort instructions.' }] },
  { id: 3, type: 'Service Bulletins', code: 'SB-ALS-2026-017', title: 'Mandatory inspection of flight-control harness', system: 'SRLM', owner: 'Quality Management', status: 'Published', version: '1.1', updated: '20 Jul 2026', effective: '25 Jul 2026', summary: 'Mandatory pre-flight harness inspection for identified production lots.', revisions: [{ version: '1.1', date: '20 Jul 2026', author: 'Deepa Reddy', note: 'Expanded affected serial-number range.' }, { version: '1.0', date: '12 Jul 2026', author: 'Deepa Reddy', note: 'Initial release.' }] },
  { id: 4, type: 'Operator Bulletins', code: 'OB-ALS-2026-009', title: 'Monsoon deployment operating precautions', system: 'SRLM', owner: 'Flight Team', status: 'Published', version: '1.0', updated: '14 Jul 2026', effective: '14 Jul 2026', summary: 'Operating precautions and recovery checks for high-humidity deployments.', revisions: [{ version: '1.0', date: '14 Jul 2026', author: 'Sneha Kulkarni', note: 'Initial operational bulletin.' }] },
  { id: 5, type: 'Amendments leaflets', code: 'AL-ALS-2026-004', title: 'Amendment: payload mounting torque values', system: 'Payload', owner: 'Hardware', status: 'Draft', version: '0.3', updated: '21 Jul 2026', effective: '--', summary: 'Proposed change to payload mounting torque table following qualification testing.', revisions: [{ version: '0.3', date: '21 Jul 2026', author: 'Sanjay Bhatia', note: 'Awaiting Quality approval.' }] },
  { id: 6, type: 'In-coming Letters', code: 'INL-IAF-2026-031', title: 'Indian Air Force request for field training schedule', system: 'Customer', owner: 'Customer Support Manager', status: 'Acknowledged', version: '1.0', updated: '19 Jul 2026', effective: '--', summary: 'Customer communication requesting a field training schedule for August 2026.', revisions: [{ version: '1.0', date: '19 Jul 2026', author: 'Priyanka Rao', note: 'Received and routed to Program Management.' }] },
  { id: 7, type: 'Out-going Letters', code: 'OUT-IAF-2026-022', title: 'Response: field training schedule and resources', system: 'Customer', owner: 'Program Management', status: 'Approved', version: '1.0', updated: '21 Jul 2026', effective: '22 Jul 2026', summary: 'Approved response confirming training dates, instructors, and required equipment.', revisions: [{ version: '1.0', date: '21 Jul 2026', author: 'Rahul Mehta', note: 'Approved for dispatch.' }] },
  { id: 8, type: 'Knowledge Articles', code: 'KA-ALS-0018', title: 'Troubleshooting intermittent telemetry loss', system: 'Communication', owner: 'Radio', status: 'Published', version: '2.0', updated: '17 Jul 2026', effective: '17 Jul 2026', summary: 'Diagnostic flow for intermittent telemetry loss observed during mission preparation.', revisions: [{ version: '2.0', date: '17 Jul 2026', author: 'Manish Gupta', note: 'Added antenna cable continuity test.' }, { version: '1.0', date: '09 Jan 2026', author: 'Manish Gupta', note: 'Initial knowledge article.' }] },
]

const emptyDocument = { type: 'Manuals', code: '', title: '', system: '', owner: '', status: 'Draft', version: '0.1', effective: '', summary: '' }

export default function KnowledgeManagementPage({ documents, setDocuments }) {
  const [activeSection, setActiveSection] = useState('Dashboard')
  const [search, setSearch] = useState('')
  const [statusFilter, setStatusFilter] = useState('All')
  const [selectedDocument, setSelectedDocument] = useState(null)
  const [editingDocument, setEditingDocument] = useState(null)
  const [newRevisionOf, setNewRevisionOf] = useState(null)

  const openDocument = (document) => { setSelectedDocument(document); setEditingDocument(null) }
  const addDocument = (document) => {
    const today = '22 Jul 2026'
    const nextDocument = { id: Math.max(0, ...documents.map((item) => item.id)) + 1, ...document, updated: today, revisions: [{ version: document.version, date: today, author: 'Amitabh Sharma', note: 'Initial draft created.' }] }
    setDocuments((current) => [nextDocument, ...current])
    setEditingDocument(null)
  }
  const saveRevision = (document) => {
    const today = '22 Jul 2026'
    setDocuments((current) => current.map((item) => item.id === newRevisionOf.id ? { ...item, ...document, updated: today, revisions: [{ version: document.version, date: today, author: 'Amitabh Sharma', note: 'New revision created.' }, ...item.revisions] } : item))
    setNewRevisionOf(null)
  }
  const updateDocument = (document) => {
    setDocuments((current) => current.map((item) => item.id === editingDocument.id ? { ...item, ...document, updated: '22 Jul 2026' } : item))
    setEditingDocument(null)
  }
  const deleteDocument = (id) => setDocuments((current) => current.filter((item) => item.id !== id))

  if (editingDocument) return <KnowledgeForm document={editingDocument} onCancel={() => setEditingDocument(null)} onSubmit={editingDocument.id ? updateDocument : addDocument} />
  if (newRevisionOf) return <KnowledgeForm document={{ ...newRevisionOf, version: nextVersion(newRevisionOf.version), status: 'Draft' }} revision onCancel={() => setNewRevisionOf(null)} onSubmit={saveRevision} />
  if (selectedDocument) return <KnowledgeDetail document={selectedDocument} onCancel={() => setSelectedDocument(null)} onNewRevision={() => { setNewRevisionOf(selectedDocument); setSelectedDocument(null) }} />

  const currentDocuments = documents.filter((document) => activeSection === 'Dashboard' || document.type === activeSection)
  const filteredDocuments = currentDocuments.filter((document) => (statusFilter === 'All' || document.status === statusFilter) && (!search || [document.code, document.title, document.system, document.owner].some((value) => value.toLowerCase().includes(search.toLowerCase()))))

  return <section className="knowledge-page">
    <aside className="knowledge-nav"><div className="knowledge-nav-title"><BookOpen size={17} /><span>Knowledge management</span></div>{sections.map(({ key, label, icon: Icon }) => <button key={key} className={activeSection === key ? 'active' : ''} onClick={() => { setActiveSection(key); setSearch(''); setStatusFilter('All') }}><Icon size={15} />{label}</button>)}</aside>
    <main className="knowledge-main">{activeSection === 'Dashboard' ? <KnowledgeDashboard documents={documents} onNavigate={setActiveSection} onOpen={openDocument} /> : <DocumentRegister title={activeSection} documents={filteredDocuments} search={search} statusFilter={statusFilter} onSearch={setSearch} onStatusFilter={setStatusFilter} onOpen={openDocument} onCreate={() => setEditingDocument({ ...emptyDocument, type: activeSection })} onEdit={(doc) => setEditingDocument(doc)} onDelete={(id) => deleteDocument(id)} />}</main>
  </section>
}

function KnowledgeDashboard({ documents, onNavigate, onOpen }) {
  const published = documents.filter((document) => document.status === 'Published').length
  const drafts = documents.filter((document) => document.status === 'Draft').length
  const actionItems = documents.filter((document) => ['Draft', 'Acknowledged'].includes(document.status)).length
  const recent = [...documents].sort((first, second) => second.updated.localeCompare(first.updated)).slice(0, 5)
  return <><header className="knowledge-header"><div><p>Knowledge management</p><h1>Knowledge dashboard</h1><span>Controlled technical content, correspondence, and operational guidance.</span></div><button className="knowledge-primary" onClick={() => onNavigate('Knowledge Articles')}><FilePlus2 size={15} /> New knowledge article</button></header><div className="knowledge-metrics"><Metric label="Published documents" value={published} icon={ShieldCheck} tone="blue" /><Metric label="Drafts awaiting review" value={drafts} icon={PenLine} tone="amber" /><Metric label="Actionable records" value={actionItems} icon={ClipboardList} tone="red" /></div><section className="knowledge-dashboard-grid"><div className="knowledge-panel"><div className="knowledge-panel-heading"><h2>Recent updates</h2><button onClick={() => onNavigate('Manuals')}>View register <ChevronRight size={14} /></button></div><div className="knowledge-activity">{recent.map((document) => <button key={document.id} onClick={() => onOpen(document)}><span className="knowledge-type-dot">{document.type.slice(0, 2).toUpperCase()}</span><span><strong>{document.title}</strong><small>{document.code} · Version {document.version} · {document.updated}</small></span><span className={`knowledge-status ${document.status.toLowerCase().replaceAll(' ', '-')}`}>{document.status}</span></button>)}</div></div><div className="knowledge-panel"><div className="knowledge-panel-heading"><h2>Content registers</h2></div><div className="knowledge-register-links">{sections.slice(1).map(({ key, label, icon: Icon }) => <button key={key} onClick={() => onNavigate(key)}><Icon size={16} /><span>{label}</span><b>{documents.filter((document) => document.type === key).length}</b><ChevronRight size={14} /></button>)}</div></div></section></>
}

function Metric({ label, value, icon: Icon, tone }) { return <div className={`knowledge-metric ${tone}`}><span><Icon size={18} /></span><div><strong>{value}</strong><small>{label}</small></div></div> }

function DocumentRegister({ title, documents, search, statusFilter, onSearch, onStatusFilter, onOpen, onCreate, onEdit, onDelete }) {
  const exportCsv = () => {
    const csv = (v) => `"${String(v ?? '').replaceAll('"', '""')}"`
    const data = [['Document Code', 'Title', 'System', 'Owner', 'Version', 'Effective Date', 'Status'].map(csv), ...documents.map((d) => [d.code, d.title, d.system, d.owner, d.version, d.effective || '', d.status].map(csv))].map((r) => r.join(',')).join('\n')
    const url = URL.createObjectURL(new Blob([data], { type: 'text/csv;charset=utf-8;' }))
    const a = document.createElement('a'); a.href = url; a.download = `${title.toLowerCase().replaceAll(' ', '-')}.csv`; a.click(); URL.revokeObjectURL(url)
  }
  return <><header className="knowledge-header"><div><p>Knowledge management / Register</p><h1>{title}</h1><span>Version-controlled records with reviewable revision history.</span></div><div style={{ display: 'flex', gap: '7px' }}><button className="compact-button secondary" onClick={exportCsv} disabled={!documents.length}><Download size={15} /> Extract data</button><button className="knowledge-primary" onClick={onCreate}><FilePlus2 size={15} /> New record</button></div></header><div className="knowledge-toolbar"><label><Search size={15} /><input value={search} onChange={(event) => onSearch(event.target.value)} placeholder={`Search ${title.toLowerCase()}...`} /></label><select value={statusFilter} onChange={(event) => onStatusFilter(event.target.value)}><option>All</option><option>Published</option><option>Draft</option><option>Approved</option><option>Acknowledged</option></select><span>{documents.length} record{documents.length === 1 ? '' : 's'}</span></div><div className="knowledge-table-frame"><table className="knowledge-table"><thead><tr><th>Document</th><th>System / area</th><th>Owner</th><th>Version</th><th>Effective date</th><th>Status</th><th>Actions</th></tr></thead><tbody>{documents.map((document) => <tr key={document.id}><td><button className="knowledge-document-link" onClick={() => onOpen(document)}>{document.title}<small>{document.code} · Updated {document.updated}</small></button></td><td>{document.system}</td><td>{document.owner}</td><td><span className="version-pill">v{document.version}</span></td><td>{document.effective || '--'}</td><td><span className={`knowledge-status ${document.status.toLowerCase().replaceAll(' ', '-')}`}>{document.status}</span></td><td className="action-buttons"><button className="icon-button" onClick={() => onOpen(document)} title="View"><ChevronRight size={15} /></button><button className="icon-button" onClick={() => onEdit(document)} title="Edit"><Edit2 size={15} /></button><button className="icon-button danger" onClick={() => onDelete(document.id)} title="Delete"><Trash2 size={15} /></button></td></tr>)}{!documents.length && <tr><td className="knowledge-empty" colSpan="7">No records match the current search and status filter.</td></tr>}</tbody></table></div></> }

function KnowledgeDetail({ document, onCancel, onNewRevision }) { return <section className="knowledge-detail"><header className="knowledge-header"><div><button className="knowledge-back" onClick={onCancel}>Knowledge management</button><p>{document.type} · {document.code}</p><h1>{document.title}</h1><span>{document.summary}</span></div><button className="knowledge-primary" onClick={onNewRevision}><History size={15} /> New revision</button></header><div className="knowledge-detail-grid"><section className="knowledge-panel knowledge-content-panel"><h2>Controlled content</h2><p>{document.summary}</p><div className="knowledge-content-meta"><span><b>System / area</b>{document.system}</span><span><b>Owner</b>{document.owner}</span><span><b>Effective date</b>{document.effective || '--'}</span><span><b>Current status</b><i className={`knowledge-status ${document.status.toLowerCase().replaceAll(' ', '-')}`}>{document.status}</i></span></div></section><section className="knowledge-panel"><div className="knowledge-panel-heading"><h2>Version history</h2><span className="version-pill">Current v{document.version}</span></div><ol className="revision-history">{document.revisions.map((revision, index) => <li key={`${revision.version}-${revision.date}`}><span>{index + 1}</span><div><strong>Version {revision.version}</strong><small>{revision.date} · {revision.author}</small><p>{revision.note}</p></div></li>)}</ol></section></div></section> }

function KnowledgeForm({ document, revision, onCancel, onSubmit }) { const [form, setForm] = useState(document); const update = (key, value) => setForm((current) => ({ ...current, [key]: value })); const submit = (event) => { event.preventDefault(); if (form.code.trim() && form.title.trim()) onSubmit(form) }; return <form className="knowledge-form" onSubmit={submit}><header className="knowledge-header"><div><button type="button" className="knowledge-back" onClick={onCancel}>Knowledge management</button><p>{form.type}</p><h1>{revision ? `New revision ${form.version}` : 'New controlled record'}</h1><span>{revision ? 'Draft the next controlled revision. The prior version remains in the history.' : 'Create a record with its initial controlled version.'}</span></div><div><button type="button" className="knowledge-secondary" onClick={onCancel}>Cancel</button><button className="knowledge-primary" type="submit">Save draft</button></div></header><section className="knowledge-form-sheet"><label>DOCUMENT TYPE<select value={form.type} onChange={(event) => update('type', event.target.value)}>{sections.slice(1).map((section) => <option key={section.key}>{section.key}</option>)}</select></label><label>DOCUMENT CODE<input value={form.code} onChange={(event) => update('code', event.target.value)} placeholder="e.g., KA-ALS-0020" required /></label><label className="full">TITLE<input value={form.title} onChange={(event) => update('title', event.target.value)} placeholder="Controlled document title" required /></label><label>SYSTEM / AREA<input value={form.system} onChange={(event) => update('system', event.target.value)} placeholder="e.g., SRLM, Customer, GCS" /></label><label>CONTENT OWNER<input value={form.owner} onChange={(event) => update('owner', event.target.value)} placeholder="Responsible group" /></label><label>VERSION<input value={form.version} onChange={(event) => update('version', event.target.value)} /></label><label>STATUS<select value={form.status} onChange={(event) => update('status', event.target.value)}><option>Draft</option><option>Published</option><option>Approved</option><option>Acknowledged</option></select></label><label>EFFECTIVE DATE<input type="date" value={form.effective} onChange={(event) => update('effective', event.target.value)} /></label><label className="full">SUMMARY<textarea value={form.summary} onChange={(event) => update('summary', event.target.value)} rows="5" placeholder="Document scope, operational impact, and key change summary" /></label></section></form> }

function nextVersion(version) { const [major, minor] = String(version).split('.').map(Number); return `${major}.${(minor || 0) + 1}` }
